/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param grantType 授权方式，`authorization_code` 需要用到code，refresh_token需要用到
 * @param clientId App ID
 * @param clientSecret App Secret
 * @param redirectUri 回调 URL
 * @param refreshToken Refresh Token
 * @param code 验证代码
 * @param state 随机参数
 */
@Serializable

data class AccessTokenRequest (

    /* 授权方式，`authorization_code` 需要用到code，refresh_token需要用到 */
    @SerialName(value = "grant_type")
    val grantType: AccessTokenRequest.GrantType,

    /* App ID */
    @SerialName(value = "client_id")
    val clientId: kotlin.String,

    /* App Secret */
    @SerialName(value = "client_secret")
    val clientSecret: kotlin.String,

    /* 回调 URL */
    @SerialName(value = "redirect_uri")
    val redirectUri: kotlin.String,

    /* Refresh Token */
    @SerialName(value = "refresh_token")
    val refreshToken: kotlin.String? = null,

    /* 验证代码 */
    @SerialName(value = "code")
    val code: kotlin.String? = null,

    /* 随机参数 */
    @SerialName(value = "state")
    val state: kotlin.String? = null

) {

    /**
     * 授权方式，`authorization_code` 需要用到code，refresh_token需要用到
     *
     * Values: AUTHORIZATION_CODE,REFRESH_TOKEN
     */
    @Serializable
    enum class GrantType(val value: kotlin.String) {
        @SerialName(value = "authorization_code") AUTHORIZATION_CODE("authorization_code"),
        @SerialName(value = "refresh_token") REFRESH_TOKEN("refresh_token");
    }

}

