/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.CharacterRevisionDataItem
import moe.kurenai.bangumi.models.Creator

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param type 
 * @param summary 
 * @param createdAt 
 * @param creator 
 * @param `data` 
 */
@Serializable

data class CharacterRevision (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "type")
    val type: kotlin.Int,

    @SerialName(value = "summary")
    val summary: kotlin.String,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "creator")
    val creator: Creator? = null,

    @Contextual @SerialName(value = "data")
    val `data`: kotlin.collections.Map<kotlin.String, CharacterRevisionDataItem>? = null

) {


}

