/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.BloodType
import moe.kurenai.bangumi.models.CharacterType
import moe.kurenai.bangumi.models.PersonImages
import moe.kurenai.bangumi.models.Stat

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param type 角色，机体，舰船，组织...
 * @param summary 
 * @param locked 
 * @param stat 
 * @param images object with some size of images, this object maybe `null`
 * @param infobox server parsed infobox, a map from key to string or tuple null if server infobox is not valid
 * @param gender parsed from wiki, maybe null
 * @param bloodType parsed from wiki, maybe null, `1, 2, 3, 4` for `A, B, AB, O`
 * @param birthYear parsed from wiki, maybe `null`
 * @param birthMon parsed from wiki, maybe `null`
 * @param birthDay parsed from wiki, maybe `null`
 */
@Serializable

data class CharacterDetail (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "name")
    val name: kotlin.String,

    /* 角色，机体，舰船，组织... */
    @Contextual @SerialName(value = "type")
    val type: CharacterType,

    @SerialName(value = "summary")
    val summary: kotlin.String,

    @SerialName(value = "locked")
    val locked: kotlin.Boolean,

    @SerialName(value = "stat")
    val stat: Stat,

    /* object with some size of images, this object maybe `null` */
    @SerialName(value = "images")
    val images: PersonImages? = null,

    /* server parsed infobox, a map from key to string or tuple null if server infobox is not valid */
    @SerialName(value = "infobox")
    val infobox: kotlin.collections.List<@Contextual kotlin.Any>? = null,

    /* parsed from wiki, maybe null */
    @SerialName(value = "gender")
    val gender: kotlin.String? = null,

    /* parsed from wiki, maybe null, `1, 2, 3, 4` for `A, B, AB, O` */
    @Contextual @SerialName(value = "blood_type")
    val bloodType: BloodType? = null,

    /* parsed from wiki, maybe `null` */
    @SerialName(value = "birth_year")
    val birthYear: kotlin.Int? = null,

    /* parsed from wiki, maybe `null` */
    @SerialName(value = "birth_mon")
    val birthMon: kotlin.Int? = null,

    /* parsed from wiki, maybe `null` */
    @SerialName(value = "birth_day")
    val birthDay: kotlin.Int? = null

) {


}

