/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.RevisionExtra

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param infobox 
 * @param summary 
 * @param name 
 * @param extra 
 */
@Serializable

data class CharacterRevisionDataItem (

    @SerialName(value = "infobox")
    val infobox: kotlin.String,

    @SerialName(value = "summary")
    val summary: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "extra")
    val extra: RevisionExtra

) {


}

