/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param wish 
 * @param collect 
 * @param doing 
 * @param onHold 
 * @param dropped 
 */
@Serializable

data class Collection (

    @SerialName(value = "wish")
    val wish: kotlin.Int,

    @SerialName(value = "collect")
    val collect: kotlin.Int,

    @SerialName(value = "doing")
    val doing: kotlin.Int,

    @SerialName(value = "on_hold")
    val onHold: kotlin.Int,

    @SerialName(value = "dropped")
    val dropped: kotlin.Int

) {


}

