/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 意义同<a href=\"#model-Me\">Me</a>
 *
 * @param username 
 * @param nickname 
 */
@Serializable

data class Creator (

    @SerialName(value = "username")
    val username: kotlin.String,

    @SerialName(value = "nickname")
    val nickname: kotlin.String

) {


}

