/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.Avatar
import moe.kurenai.bangumi.models.UserGroup

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param username 唯一用户名，初始与 UID 相同，可修改一次
 * @param nickname 
 * @param userGroup 
 * @param avatar 
 * @param sign 个人签名
 * @param timeOffset 用户设置的时区偏移，以小时为单位。比如 GMT+8（shanghai/beijing）为 8
 */
@Serializable

data class GetMyself200Response (

    @SerialName(value = "id")
    val id: kotlin.Int,

    /* 唯一用户名，初始与 UID 相同，可修改一次 */
    @SerialName(value = "username")
    val username: kotlin.String,

    @SerialName(value = "nickname")
    val nickname: kotlin.String,

    @Contextual @SerialName(value = "user_group")
    val userGroup: UserGroup,

    @SerialName(value = "avatar")
    val avatar: Avatar,

    /* 个人签名 */
    @SerialName(value = "sign")
    val sign: kotlin.String,

    /* 用户设置的时区偏移，以小时为单位。比如 GMT+8（shanghai/beijing）为 8 */
    @SerialName(value = "time_offset")
    val timeOffset: kotlin.Int? = null

) {


}

