/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.Creator
import moe.kurenai.bangumi.models.Stat

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param title 
 * @param desc 
 * @param stat 目录评论及收藏数
 * @param createdAt 
 * @param updatedAt 
 * @param creator 
 * @param ban deprecated, always false.
 * @param nsfw 
 * @param total 收录条目总数
 */
@Serializable

data class Index (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "desc")
    val desc: kotlin.String,

    /* 目录评论及收藏数 */
    @SerialName(value = "stat")
    val stat: Stat,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @SerialName(value = "creator")
    val creator: Creator,

    /* deprecated, always false. */
    @SerialName(value = "ban")
    @Deprecated(message = "This property is deprecated.")
    val ban: kotlin.Boolean,

    @SerialName(value = "nsfw")
    val nsfw: kotlin.Boolean,

    /* 收录条目总数 */
    @SerialName(value = "total")
    val total: kotlin.Int? = 0

) {


}

