/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 新增或修改条目的内容，同名字段意义同<a href=\"#model-Subject\">Subject</a>
 *
 * @param title 
 * @param description 
 */
@Serializable

data class IndexBasicInfo (

    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null

) {


}

