/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.Images
import moe.kurenai.bangumi.models.Item

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 同名字段意义同<a href=\"#model-Subject\">Subject</a>
 *
 * @param id 
 * @param type 
 * @param name 
 * @param comment 
 * @param addedAt 
 * @param images 
 * @param infobox 
 * @param date 
 */
@Serializable

data class IndexSubject (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "type")
    val type: kotlin.Int,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "comment")
    val comment: kotlin.String,

    @Contextual @SerialName(value = "added_at")
    val addedAt: java.time.OffsetDateTime,

    @SerialName(value = "images")
    val images: Images? = null,

    @SerialName(value = "infobox")
    val infobox: kotlin.collections.List<Item>? = null,

    @SerialName(value = "date")
    val date: kotlin.String? = null

) {


}

