/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.LegacyUser

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 日志
 *
 * @param id ID
 * @param url 地址
 * @param title 标题
 * @param summary 概览
 * @param image 图片
 * @param replies 回复数
 * @param timestamp 发布时间
 * @param dateline 发布时间
 * @param user 
 */
@Serializable

data class LegacyBlog (

    /* ID */
    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    /* 地址 */
    @SerialName(value = "url")
    val url: kotlin.String? = null,

    /* 标题 */
    @SerialName(value = "title")
    val title: kotlin.String? = null,

    /* 概览 */
    @SerialName(value = "summary")
    val summary: kotlin.String? = null,

    /* 图片 */
    @SerialName(value = "image")
    val image: kotlin.String? = null,

    /* 回复数 */
    @SerialName(value = "replies")
    val replies: kotlin.Int? = null,

    /* 发布时间 */
    @SerialName(value = "timestamp")
    val timestamp: kotlin.Int? = null,

    /* 发布时间 */
    @SerialName(value = "dateline")
    val dateline: kotlin.String? = null,

    @SerialName(value = "user")
    val user: LegacyUser? = null

) {


}

