/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.LegacyUserAvatar
import moe.kurenai.bangumi.models.LegacyUserGroup

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 用户信息
 *
 * @param id 用户 id
 * @param url 用户主页地址
 * @param username 用户名
 * @param nickname 昵称
 * @param avatar 
 * @param sign 签名
 * @param usergroup 
 */
@Serializable

data class LegacyUser (

    /* 用户 id */
    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    /* 用户主页地址 */
    @SerialName(value = "url")
    val url: kotlin.String? = null,

    /* 用户名 */
    @SerialName(value = "username")
    val username: kotlin.String? = null,

    /* 昵称 */
    @SerialName(value = "nickname")
    val nickname: kotlin.String? = null,

    @SerialName(value = "avatar")
    val avatar: LegacyUserAvatar? = null,

    /* 签名 */
    @SerialName(value = "sign")
    val sign: kotlin.String? = null,

    @Contextual @SerialName(value = "usergroup")
    val usergroup: LegacyUserGroup? = null

) {


}

