/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.LegacyMonoBaseImages
import moe.kurenai.bangumi.models.LegacyMonoInfo

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 人物 ID
 * @param url 人物地址
 * @param name 姓名
 * @param images 
 * @param nameCn 简体中文名
 * @param comment 回复数量
 * @param collects 收藏人数
 * @param info 
 * @param roleName 人物类型
 * @param jobs 职位
 */
@Serializable

data class LegacySubjectMediumAllOfStaff (

    /* 人物 ID */
    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    /* 人物地址 */
    @SerialName(value = "url")
    val url: kotlin.String? = null,

    /* 姓名 */
    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "images")
    val images: LegacyMonoBaseImages? = null,

    /* 简体中文名 */
    @SerialName(value = "name_cn")
    val nameCn: kotlin.String? = null,

    /* 回复数量 */
    @SerialName(value = "comment")
    val comment: kotlin.Int? = null,

    /* 收藏人数 */
    @SerialName(value = "collects")
    val collects: kotlin.Int? = null,

    @SerialName(value = "info")
    val info: LegacyMonoInfo? = null,

    /* 人物类型 */
    @SerialName(value = "role_name")
    val roleName: kotlin.String? = null,

    /* 职位 */
    @SerialName(value = "jobs")
    val jobs: kotlin.collections.List<kotlin.String>? = null

) {


}

