/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.LegacyUser

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 讨论版
 *
 * @param id ID
 * @param url 地址
 * @param title 标题
 * @param mainId 所属对象（条目） ID
 * @param timestamp 发布时间
 * @param lastpost 最后回复时间
 * @param replies 回复数
 * @param user 
 */
@Serializable

data class LegacyTopic (

    /* ID */
    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    /* 地址 */
    @SerialName(value = "url")
    val url: kotlin.String? = null,

    /* 标题 */
    @SerialName(value = "title")
    val title: kotlin.String? = null,

    /* 所属对象（条目） ID */
    @SerialName(value = "main_id")
    val mainId: kotlin.Int? = null,

    /* 发布时间 */
    @SerialName(value = "timestamp")
    val timestamp: kotlin.Int? = null,

    /* 最后回复时间 */
    @SerialName(value = "lastpost")
    val lastpost: kotlin.Int? = null,

    /* 回复数 */
    @SerialName(value = "replies")
    val replies: kotlin.Int? = null,

    @SerialName(value = "user")
    val user: LegacyUser? = null

) {


}

