/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 肖像
 *
 * @param large 
 * @param medium 
 * @param small 
 * @param grid 
 */
@Serializable

data class LegacyMonoBaseImages (

    @SerialName(value = "large")
    val large: kotlin.String? = null,

    @SerialName(value = "medium")
    val medium: kotlin.String? = null,

    @SerialName(value = "small")
    val small: kotlin.String? = null,

    @SerialName(value = "grid")
    val grid: kotlin.String? = null

) {


}

