/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 别名（另外添加出来的 key 为 0 开始的数字）
 *
 * @param jp 日文名
 * @param kana 纯假名
 * @param nick 昵称
 * @param romaji 罗马字
 * @param zh 第二中文名
 */
@Serializable

data class LegacyMonoInfoAlias (

    /* 日文名 */
    @SerialName(value = "jp")
    val jp: kotlin.String? = null,

    /* 纯假名 */
    @SerialName(value = "kana")
    val kana: kotlin.String? = null,

    /* 昵称 */
    @SerialName(value = "nick")
    val nick: kotlin.String? = null,

    /* 罗马字 */
    @SerialName(value = "romaji")
    val romaji: kotlin.String? = null,

    /* 第二中文名 */
    @SerialName(value = "zh")
    val zh: kotlin.String? = null

) {


}

