/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.LegacyMonoInfoAlias
import moe.kurenai.bangumi.models.LegacyMonoInfoSource

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 人物信息
 *
 * @param birth 生日
 * @param height 身高
 * @param gender 性别
 * @param alias 
 * @param source 
 * @param nameCn 简体中文名
 * @param cv 声优
 */
@Serializable

data class LegacyMonoInfo (

    /* 生日 */
    @SerialName(value = "birth")
    val birth: kotlin.String? = null,

    /* 身高 */
    @SerialName(value = "height")
    val height: kotlin.String? = null,

    /* 性别 */
    @SerialName(value = "gender")
    val gender: kotlin.String? = null,

    @SerialName(value = "alias")
    val alias: LegacyMonoInfoAlias? = null,

    @SerialName(value = "source")
    val source: LegacyMonoInfoSource? = null,

    /* 简体中文名 */
    @SerialName(value = "name_cn")
    val nameCn: kotlin.String? = null,

    /* 声优 */
    @SerialName(value = "cv")
    val cv: kotlin.String? = null

) {


}

