/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.LegacyEpisodeType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 章节信息
 *
 * @param id 章节 ID
 * @param url 章节地址
 * @param type 
 * @param sort 集数
 * @param name 标题
 * @param nameCn 简体中文标题
 * @param duration 时长
 * @param airdate 放送日期
 * @param comment 回复数量
 * @param desc 简介
 * @param status 放送状态 <br> Air = 已放送 <br> Today = 正在放送 <br> NA = 未放送
 */
@Serializable

data class LegacyEpisode (

    /* 章节 ID */
    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    /* 章节地址 */
    @SerialName(value = "url")
    val url: kotlin.String? = null,

    @Contextual @SerialName(value = "type")
    val type: LegacyEpisodeType? = null,

    /* 集数 */
    @SerialName(value = "sort")
    val sort: kotlin.Int? = null,

    /* 标题 */
    @SerialName(value = "name")
    val name: kotlin.String? = null,

    /* 简体中文标题 */
    @SerialName(value = "name_cn")
    val nameCn: kotlin.String? = null,

    /* 时长 */
    @SerialName(value = "duration")
    val duration: kotlin.String? = null,

    /* 放送日期 */
    @SerialName(value = "airdate")
    val airdate: kotlin.String? = null,

    /* 回复数量 */
    @SerialName(value = "comment")
    val comment: kotlin.Int? = null,

    /* 简介 */
    @SerialName(value = "desc")
    val desc: kotlin.String? = null,

    /* 放送状态 <br> Air = 已放送 <br> Today = 正在放送 <br> NA = 未放送 */
    @SerialName(value = "status")
    val status: LegacyEpisode.Status? = null

) {

    /**
     * 放送状态 <br> Air = 已放送 <br> Today = 正在放送 <br> NA = 未放送
     *
     * Values: AIR,TODAY,NA
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "Air") AIR("Air"),
        @SerialName(value = "Today") TODAY("Today"),
        @SerialName(value = "NA") NA("NA");
    }

}

