/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.LegacyMonoBaseImages

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 人物（基础模型）
 *
 * @param id 人物 ID
 * @param url 人物地址
 * @param name 姓名
 * @param images 
 */
@Serializable

data class LegacyMonoBase (

    /* 人物 ID */
    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    /* 人物地址 */
    @SerialName(value = "url")
    val url: kotlin.String? = null,

    /* 姓名 */
    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "images")
    val images: LegacyMonoBaseImages? = null

) {


}

