/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 条目类型 <br> 1 = book <br> 2 = anime <br> 3 = music <br> 4 = game <br> 6 = real
 *
 * Values: _1,_2,_3,_4,_6
 */
@Serializable
enum class LegacySubjectType(val value: kotlin.Int) {

    @SerialName(value = "1")
    _1(1),

    @SerialName(value = "2")
    _2(2),

    @SerialName(value = "3")
    _3(3),

    @SerialName(value = "4")
    _4(4),

    @SerialName(value = "6")
    _6(6);

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value.toString()

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is LegacySubjectType) "$data" else null

        /**
         * Returns a valid [LegacySubjectType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): LegacySubjectType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

