/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.EpisodeCollectionType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param episodeId 
 * @param type 
 */
@Serializable

data class PatchUserSubjectEpisodeCollectionRequest (

    @SerialName(value = "episode_id")
    val episodeId: kotlin.collections.List<kotlin.Int>,

    @Contextual @SerialName(value = "type")
    val type: EpisodeCollectionType

) {


}

