/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.PersonRevisionProfession
import moe.kurenai.bangumi.models.RevisionExtra

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param prsnInfobox 
 * @param prsnSummary 
 * @param profession 
 * @param extra 
 * @param prsnName 
 */
@Serializable

data class PersonRevisionDataItem (

    @SerialName(value = "prsn_infobox")
    val prsnInfobox: kotlin.String,

    @SerialName(value = "prsn_summary")
    val prsnSummary: kotlin.String,

    @SerialName(value = "profession")
    val profession: PersonRevisionProfession,

    @SerialName(value = "extra")
    val extra: RevisionExtra,

    @SerialName(value = "prsn_name")
    val prsnName: kotlin.String

) {


}

