/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.CharacterType
import moe.kurenai.bangumi.models.PersonImages
import moe.kurenai.bangumi.models.SubjectType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param type 角色，机体，舰船，组织...
 * @param subjectId 
 * @param subjectType 
 * @param subjectName 
 * @param subjectNameCn 
 * @param images object with some size of images, this object maybe `null`
 * @param staff 
 */
@Serializable

data class PersonCharacter (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "name")
    val name: kotlin.String,

    /* 角色，机体，舰船，组织... */
    @Contextual @SerialName(value = "type")
    val type: CharacterType,

    @SerialName(value = "subject_id")
    val subjectId: kotlin.Int,

    @Contextual @SerialName(value = "subject_type")
    val subjectType: SubjectType,

    @SerialName(value = "subject_name")
    val subjectName: kotlin.String,

    @SerialName(value = "subject_name_cn")
    val subjectNameCn: kotlin.String,

    /* object with some size of images, this object maybe `null` */
    @SerialName(value = "images")
    val images: PersonImages? = null,

    @SerialName(value = "staff")
    val staff: kotlin.String? = null

) {


}

