/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.Count

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param rank 
 * @param total 
 * @param count 
 * @param score 
 */
@Serializable

data class Rating (

    @SerialName(value = "rank")
    val rank: kotlin.Int,

    @SerialName(value = "total")
    val total: kotlin.Int,

    @SerialName(value = "count")
    val count: Count,

    @Contextual @SerialName(value = "score")
    val score: java.math.BigDecimal

) {


}

