/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.SearchSubjects200ResponseDataInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 用户信息
 *
 * @param total 搜索结果数量
 * @param limit 当前分页参数
 * @param offset 当前分页参数
 * @param `data` 
 */
@Serializable

data class SearchSubjects200Response (

    /* 搜索结果数量 */
    @SerialName(value = "total")
    val total: kotlin.Int? = null,

    /* 当前分页参数 */
    @SerialName(value = "limit")
    val limit: kotlin.Int? = null,

    /* 当前分页参数 */
    @SerialName(value = "offset")
    val offset: kotlin.Int? = null,

    @SerialName(value = "data")
    val `data`: kotlin.collections.List<SearchSubjects200ResponseDataInner>? = null

) {


}

