/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.SearchSubjectsRequestFilter

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param keyword 
 * @param sort 排序规则  - `match` meilisearch 的默认排序，按照匹配程度 - `heat` 收藏人数 - `rank` 排名由高到低 - `score` 评分 
 * @param filter 
 */
@Serializable

data class SearchSubjectsRequest (

    @SerialName(value = "keyword")
    val keyword: kotlin.String,

    /* 排序规则  - `match` meilisearch 的默认排序，按照匹配程度 - `heat` 收藏人数 - `rank` 排名由高到低 - `score` 评分  */
    @SerialName(value = "sort")
    val sort: SearchSubjectsRequest.Sort? = Sort.MATCH,

    @SerialName(value = "filter")
    val filter: SearchSubjectsRequestFilter? = null

) {

    /**
     * 排序规则  - `match` meilisearch 的默认排序，按照匹配程度 - `heat` 收藏人数 - `rank` 排名由高到低 - `score` 评分 
     *
     * Values: MATCH,HEAT,RANK,SCORE
     */
    @Serializable
    enum class Sort(val value: kotlin.String) {
        @SerialName(value = "match") MATCH("match"),
        @SerialName(value = "heat") HEAT("heat"),
        @SerialName(value = "rank") RANK("rank"),
        @SerialName(value = "score") SCORE("score");
    }

}

