/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.SubjectType
import moe.kurenai.bangumi.models.Tag

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 条目ID
 * @param date 上映/开播/连载开始日期，可能为空字符串
 * @param image 封面
 * @param summary 条目描述
 * @param name 条目原名
 * @param nameCn 条目中文名
 * @param tags 
 * @param score 评分
 * @param rank 排名
 * @param type 
 */
@Serializable

data class SearchSubjects200ResponseDataInner (

    /* 条目ID */
    @SerialName(value = "id")
    val id: kotlin.Int,

    /* 上映/开播/连载开始日期，可能为空字符串 */
    @SerialName(value = "date")
    val date: kotlin.String,

    /* 封面 */
    @SerialName(value = "image")
    val image: kotlin.String,

    /* 条目描述 */
    @SerialName(value = "summary")
    val summary: kotlin.String,

    /* 条目原名 */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* 条目中文名 */
    @SerialName(value = "name_cn")
    val nameCn: kotlin.String,

    @SerialName(value = "tags")
    val tags: kotlin.collections.List<Tag>,

    /* 评分 */
    @Contextual @SerialName(value = "score")
    val score: java.math.BigDecimal,

    /* 排名 */
    @SerialName(value = "rank")
    val rank: kotlin.Int,

    @Contextual @SerialName(value = "type")
    val type: SubjectType? = null

) {


}

