/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.Images
import moe.kurenai.bangumi.models.SubjectType
import moe.kurenai.bangumi.models.Tag

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param type 
 * @param name 
 * @param nameCn 
 * @param shortSummary 截短后的条目描述。
 * @param images 
 * @param volumes 书籍条目的册数，由旧服务端从wiki中解析
 * @param eps 由旧服务端从wiki中解析，对于书籍条目为`话数`
 * @param collectionTotal 收藏人数
 * @param score 分数
 * @param rank 排名
 * @param tags 前 10 个 tag
 * @param date air date in `YYYY-MM-DD` format
 */
@Serializable

data class SlimSubject (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @Contextual @SerialName(value = "type")
    val type: SubjectType,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "name_cn")
    val nameCn: kotlin.String,

    /* 截短后的条目描述。 */
    @SerialName(value = "short_summary")
    val shortSummary: kotlin.String,

    @SerialName(value = "images")
    val images: Images,

    /* 书籍条目的册数，由旧服务端从wiki中解析 */
    @SerialName(value = "volumes")
    val volumes: kotlin.Int,

    /* 由旧服务端从wiki中解析，对于书籍条目为`话数` */
    @SerialName(value = "eps")
    val eps: kotlin.Int,

    /* 收藏人数 */
    @SerialName(value = "collection_total")
    val collectionTotal: kotlin.Int,

    /* 分数 */
    @Contextual @SerialName(value = "score")
    val score: java.math.BigDecimal,

    /* 排名 */
    @SerialName(value = "rank")
    val rank: kotlin.Int,

    /* 前 10 个 tag */
    @SerialName(value = "tags")
    val tags: kotlin.collections.List<Tag>,

    /* air date in `YYYY-MM-DD` format */
    @SerialName(value = "date")
    val date: kotlin.String? = null

) {


}

