/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param fieldEps 
 * @param fieldInfobox 
 * @param fieldSummary 
 * @param name 
 * @param nameCn 
 * @param platform 
 * @param subjectId 
 * @param type 
 * @param typeId 
 * @param voteField 
 */
@Serializable

data class SubjectRevisionData (

    @SerialName(value = "field_eps")
    val fieldEps: kotlin.Int,

    @SerialName(value = "field_infobox")
    val fieldInfobox: kotlin.String,

    @SerialName(value = "field_summary")
    val fieldSummary: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "name_cn")
    val nameCn: kotlin.String,

    @SerialName(value = "platform")
    val platform: kotlin.Int,

    @SerialName(value = "subject_id")
    val subjectId: kotlin.Int,

    @SerialName(value = "type")
    val type: kotlin.Int,

    @SerialName(value = "type_id")
    val typeId: kotlin.Int,

    @SerialName(value = "vote_field")
    val voteField: kotlin.String

) {


}

