/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 书籍类型 - `0` 为 其他 - `1001` 为 漫画 - `1002` 为 小说 - `1003` 为 画集
 *
 * Values: Other,Comic,Novel,Illustration
 */
@Serializable
enum class SubjectBookCategory(val value: kotlin.Int) {

    @SerialName(value = "0")
    Other(0),

    @SerialName(value = "1001")
    Comic(1001),

    @SerialName(value = "1002")
    Novel(1002),

    @SerialName(value = "1003")
    Illustration(1003);

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value.toString()

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SubjectBookCategory) "$data" else null

        /**
         * Returns a valid [SubjectBookCategory] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SubjectBookCategory? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

