/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.SlimSubject
import moe.kurenai.bangumi.models.SubjectCollectionType
import moe.kurenai.bangumi.models.SubjectType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param subjectId 
 * @param subjectType 
 * @param rate 
 * @param type 
 * @param tags 
 * @param epStatus 
 * @param volStatus 
 * @param updatedAt 本时间并不代表条目的收藏时间。修改评分，评价，章节观看状态等收藏信息时未更新此时间是一个 bug。请不要依赖此特性
 * @param `private` 
 * @param comment 
 * @param subject 
 */
@Serializable

data class UserSubjectCollection (

    @SerialName(value = "subject_id")
    val subjectId: kotlin.Int,

    @Contextual @SerialName(value = "subject_type")
    val subjectType: SubjectType,

    @SerialName(value = "rate")
    val rate: kotlin.Int,

    @Contextual @SerialName(value = "type")
    val type: SubjectCollectionType,

    @SerialName(value = "tags")
    val tags: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "ep_status")
    val epStatus: kotlin.Int,

    @SerialName(value = "vol_status")
    val volStatus: kotlin.Int,

    /* 本时间并不代表条目的收藏时间。修改评分，评价，章节观看状态等收藏信息时未更新此时间是一个 bug。请不要依赖此特性 */
    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @SerialName(value = "private")
    val `private`: kotlin.Boolean,

    @SerialName(value = "comment")
    val comment: kotlin.String? = null,

    @SerialName(value = "subject")
    val subject: SlimSubject? = null

) {


}

