/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.PersonCareer
import moe.kurenai.bangumi.models.PersonImages
import moe.kurenai.bangumi.models.PersonType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param type `1`, `2`, `3` 表示 `个人`, `公司`, `组合`
 * @param career 
 * @param createdAt 
 * @param images object with some size of images, this object maybe `null`
 */
@Serializable

data class UserPersonCollection (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "name")
    val name: kotlin.String,

    /* `1`, `2`, `3` 表示 `个人`, `公司`, `组合` */
    @Contextual @SerialName(value = "type")
    val type: PersonType,

    @SerialName(value = "career")
    val career: kotlin.collections.List<@Contextual PersonCareer>,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* object with some size of images, this object maybe `null` */
    @SerialName(value = "images")
    val images: PersonImages? = null

) {


}

