/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param accessToken 
 * @param expiresIn 
 * @param refreshToken 
 * @param userId 
 */
@Serializable

data class UserAccessToken (

    @SerialName(value = "access_token")
    val accessToken: kotlin.String,

    @SerialName(value = "expires_in")
    val expiresIn: kotlin.Long,

    @SerialName(value = "refresh_token")
    val refreshToken: kotlin.String,

    @SerialName(value = "user_id")
    val userId: kotlin.Int

) {


}

