/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.Avatar
import moe.kurenai.bangumi.models.UserGroup

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 实际的返回值可能包括文档未声明的 `url` 字段，此字段主要用于开发者从 api 响应直接转跳到网页。 客户端开发者请不用依赖于此特性，此字段的值随时可能会改变。 
 *
 * @param id 
 * @param username 唯一用户名，初始与 UID 相同，可修改一次
 * @param nickname 
 * @param userGroup 
 * @param avatar 
 * @param sign 个人签名
 */
@Serializable

data class User (

    @SerialName(value = "id")
    val id: kotlin.Int,

    /* 唯一用户名，初始与 UID 相同，可修改一次 */
    @SerialName(value = "username")
    val username: kotlin.String,

    @SerialName(value = "nickname")
    val nickname: kotlin.String,

    @Contextual @SerialName(value = "user_group")
    val userGroup: UserGroup,

    @SerialName(value = "avatar")
    val avatar: Avatar,

    /* 个人签名 */
    @SerialName(value = "sign")
    val sign: kotlin.String

) {


}

