/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.SubjectType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param type 
 * @param staff 
 * @param name 
 * @param nameCn 
 * @param image 
 */
@Serializable

data class V0RelatedSubject (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @Contextual @SerialName(value = "type")
    val type: SubjectType,

    @SerialName(value = "staff")
    val staff: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "name_cn")
    val nameCn: kotlin.String,

    @SerialName(value = "image")
    val image: kotlin.String? = null

) {


}

