/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.Images

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param type 
 * @param name 
 * @param nameCn 
 * @param relation 
 * @param images 
 */
@Serializable

data class V0SubjectRelation (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "type")
    val type: kotlin.Int,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "name_cn")
    val nameCn: kotlin.String,

    @SerialName(value = "relation")
    val relation: kotlin.String,

    @SerialName(value = "images")
    val images: Images? = null

) {


}

