/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import moe.kurenai.bangumi.models.KV
import moe.kurenai.bangumi.models.V

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param k 
 * @param v 
 */
@Serializable

data class ValueAnyOfInner (

    @SerialName(value = "k")
    val k: kotlin.String,

    @SerialName(value = "v")
    val v: kotlin.String

) {


}

